import { defineConfig } from "vite";
import path from "path";
import materias from "./src/config/materia-links.json";
import materiaSublinks from "./src/config/materia-sublinks.json";

// mainInputs como array de pares
const mainInputs = Object.entries(materias).map(([name, filePath]) => [
  name,
  path.resolve(__dirname, filePath),
]);

// subInputs também como array de pares
const subInputs = Object.entries(materiaSublinks).flatMap(([materia, linksBySub]) =>
  Object.entries(linksBySub).flatMap(([subMateria, links]) =>
    Object.entries(links).map(([name, filePath]) => {
      const safeKey = `${materia}-${subMateria}-${name}`.replace(/\s+/g, "_").replace(/:/g, "")
      return [safeKey, path.resolve(__dirname, filePath)]
    })
  )
)

// junta os dois arrays e só depois converte em objeto
const input = Object.fromEntries([...mainInputs, ...subInputs]);

export default defineConfig({
  build: {
    rollupOptions: {
      input,
    },
    outDir: "dist", // Final folder generated by the build
  },
  resolve: {
    alias: {
      "@images": path.resolve(__dirname, "src/assets/images"),
    },
  },
});